{% set name = "ndvi2gif" %}
{% set version = "0.2.0" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2ad9ccc4ba599a859c03fd97e5cc0ece4c12e963dcd64c4d1c8b892a3b533779

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >={{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - geemap >=0.29.5
    - earthengine-api
    - geopandas
    - pandas
    - matplotlib

test:
  imports:
    - ndvi2gif
  requires:
    - python >={{ python_min }}

about:
  home: https://github.com/Digdgeo/Ndvi2Gif
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python library to create multi seasonal index composites of Earth Observation indexes from satellite data
  doc_url: https://github.com/Digdgeo/Ndvi2Gif
  dev_url: https://github.com/Digdgeo/Ndvi2Gif

extra:
  recipe-maintainers:
    - Digdgeo

