{% set name = "ndvi2gif" %}
{% set version = "0.1.1" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 684bbc06c3084b824762c8fc798ac0f122dd89e391afdfb876c0f7c5e10b70c6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - {{ pin_compatible('python', min_pin=python_min) }}
    - pip
    - setuptools
    - wheel
  run:
    - {{ pin_compatible('python', min_pin=python_min) }}
    - geemap >=0.29.5

test:
  imports:
    - ndvi2gif

about:
  home: https://github.com/Digdgeo/Ndvi2Gif
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package to create NDVI seasonal composites, and download them as GIF and GeoTIFF
  doc_url: https://github.com/Digdgeo/Ndvi2Gif
  dev_url: https://github.com/Digdgeo/Ndvi2Gif

extra:
  recipe-maintainers:
    - Digdgeo
