{% set name = "ndvi2gif" %}
{% set version = "0.1.1" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 300e5495d0306f472c1aa34a522273e3066b9f50d3eb25cee17cd3b6177eea54

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - geemap >=0.29.5

test:
  imports:
    - ndvi2gif

about:
  home: https://github.com/Digdgeo/Ndvi2Gif
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package to create NDVI seasonal composites, and download them as GIF and GeoTIFF
  doc_url: https://github.com/Digdgeo/Ndvi2Gif
  dev_url: https://github.com/Digdgeo/Ndvi2Gif

extra:
  recipe-maintainers:
    - Digdgeo