{% set name = "ndvi2gif" %}
{% set version = "0.2.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2ad9ccc4ba599a859c03fd97e5cc0ece4c12e963dcd64c4d1c8b892a3b533779

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >={{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - ndvi2gif

about:
  home: https://github.com/Digdgeo/Ndvi2Gif
  summary: Python library to create multi seasonal index composites
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - Digdgeo
